### ISSUE TITLE
Support for Raspbian GNU/Linux 12 (bookworm)?

### ISSUE THREAD

**Issue by g6nhu** [glaukos78/dxspider_installation_v2#5]
Hi,
Can this be updated for the Raspberry Pi OS please?

"Your OS distribution Raspbian GNU/Linux 12 (bookworm) is not supported"

Thanks.

**Comment by glaukos78** [comment]
Hi,

The version is supported now.

Thnaks

**Comment by g6nhu** [comment]
Thanks, I now get the following chown warning during build which I don't recall previously:

HEAD is now at 9fb58f4a add CTY-3304
Already up to date.
branch 'mojo' set up to track 'origin/mojo'.
Switched to a new branch 'mojo'
chown: warning: '.' should be ':': ‘sysop.spider’
Please enter CallSign for DxCluster: 



/edit - I assume this is when the script runs the su - sysop -c "chown -R sysop.spider spider" command.  I've manually run this using a colon instead of a full stop and it's all working as expected.
