### ISSUE TITLE
Maybe also include installation of libdbd-mysql-perl

### ISSUE THREAD

**Issue by videobuff** [glaukos78/dxspider_installation_v2#6]
I ran the script on a new fresh server with debian 12 installd.
Everything works and within half an hour i was up and running.

However, i noticed nhat the mysql database was not getting any spots.
Although i had the mysql missive enabled in DXVars.pm

In the end that turned out to be missing libdbd-mysql-perl.

**Comment by glaukos78** [comment]
Hi, 

Can add the specific library into script.

**Comment by glaukos78** [comment]
Add libraries libdbd-mysql-perl libdbd-mariadb-perl in the new version of installation script
